# 기본 Python 대 NumPy

## 행렬 나타내기

행렬 또는 벡터 개념은 컴퓨터 내에서의 시간과 공간 구현에 있어서 필수적으로 사용된다.

행렬은 파이썬에 기본적으로 내장된 자료형인 List 또는 NumPy의 array로 표현된다.

In [1]:
arr1 = [1, 3, 5, 7]
arr2 = [[1, 3], [5, 7]]

In [2]:
print(arr1)

[1, 3, 5, 7]


In [3]:
print(arr2)

[[1, 3], [5, 7]]


In [4]:
import numpy as np
arr3 = np.array(arr1)
arr4 = np.array(arr2)

In [5]:
print(arr3)

[1 3 5 7]


In [7]:
print(arr4)

[[1 3]
 [5 7]]


## 행렬 간 합(+) 연산

행렬 간 합 연산은 리스트의 조건제시법을 이용하여 만들어야 한다.

NumPy를 이용하면 단순히 합 연산으로 이를 실행할 수 있다.

조건: 각 행렬은 행과 열의 개수가 같아야 더할 수 있다.

In [11]:
arr5 = [1, 3, 5, 7]
arr6 = [2, 4, 6, 8]

In [12]:
print([x+y for x, y in zip(arr5, arr6)])

[3, 7, 11, 15]


In [13]:
arr7 = np.array(arr5)
arr8 = np.array(arr6)

In [14]:
print(arr7 + arr8)

[ 3  7 11 15]


## 행렬과 (스칼라) 정수 간 곱(\*) 연산

행렬 간 곱 연산 역시 리스트의 조건제시법을 이용하여 수행할 수 있다.

NumPy를 이용하면 단순히 정수에 행렬을 곱하면 된다.

In [15]:
arr9 = [30, 32, 34, 36, 38]

In [16]:
print([3*x for x in arr9])

[90, 96, 102, 108, 114]


In [17]:
arr10 = np.array(arr9)

In [18]:
print(3*arr10)

[ 90  96 102 108 114]


## 행렬의 각 원소끼리의 곱 연산

행렬의 각 원소끼리 곱하는 것은 엄밀히 말해서 행렬곱은 아니다.

하지만 필요하다면 NumPy에서 다음과 같이 실행할 수 있다.

In [20]:
arr11 = [[1, 3, 5], [2, 4, 6], [3, 6, 9]]
arr12 = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [21]:
print(np.array(arr11)*np.array(arr12))

[[1 0 0]
 [0 4 0]
 [0 0 9]]


## 수학의 행렬곱 연산

수학의 행렬 곱 연산은 곱해지는 왼쪽 행렬의 행, 오른쪽 행렬의 열을 각각 곱한 후 더하는 방식으로 이루어진다.

곱해지는 꼴이 달라서 혼란스러울 수 있는데 이때 오른쪽 행렬을 전치(transpose)시켜서 계산할 수 있다.

다음과 같이 함수를 만들어서 행렬 곱을 구할 수도 있고, NumPy에 내장된 dot 함수를 이용하는 방법도 있다.

In [22]:
def transpose(arr):
    temp_arr = []
    for i in range(len(arr[0])):
        temp_row = []
        for j in range(len(arr)):
            temp_row.append(arr[j][i])
        temp_arr.append(temp_row)
    return temp_arr

def multiplication(arr1, arr2):
    temp = 0
    for i in range(len(arr1)):
        temp += arr1[i]*arr2[i]
    return temp

def multiplication_of_arr(arr1, arr2):
    answer = []
    arr2_t = transpose(arr2)
    for i in range(len(arr1)):
        temp_row = []
        for j in range(len(arr2_t)):
            temp_row.append(multiplication(arr1[i], arr2_t[j]))
        answer.append(temp_row)
    return answer

In [23]:
print(multiplication_of_arr(arr11, arr12))

[[1, 3, 5], [2, 4, 6], [3, 6, 9]]


In [24]:
print(np.array(arr11).dot(arr12))

[[1 3 5]
 [2 4 6]
 [3 6 9]]


## 전치행렬

전치행렬은 기존 행렬의 행과 열을 뒤집은 꼴을 가진다.

이는 행렬의 곱 연산 및 다른 행렬 연산에서 사용될 수 있다.

In [25]:
arr13 = [[10, 12], [14, 16], [18, 20]]
print(transpose(arr13))

[[10, 14, 18], [12, 16, 20]]


In [27]:
print(np.array(arr13).T)

[[10 14 18]
 [12 16 20]]


## 영행렬, 단위행렬 등 특수한 행렬 만들기

영행렬은 행렬의 모든 원소가 0인 행렬이고, 단위행렬은 행렬의 행과 열의 개수가 같고 대각선꼴이 1, 나머지 원소가 0이다.

NumPy는 이 기능을 기본적으로 지원한다.

In [40]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
print(np.ones((4, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [54]:
print(np.eye((10)))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [45]:
print(np.arange(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


## NumPy로 무작위 숫자 만들기

### 정규분포 (rows, columns)

In [48]:
data = 100 + np.random.randn(5,5) * 15
data

array([[ 60.31400312, 123.21481206,  74.18427858, 119.13657838,
         92.92578533],
       [109.42750566, 125.1664202 , 103.93002561, 108.80094921,
        107.82576544],
       [102.65178632, 104.73313351, 117.38513352, 120.4698745 ,
        117.82637804],
       [ 80.58729481,  84.55777487, 108.98867894,  66.36638487,
        121.70176255],
       [ 96.71478568, 104.8900797 ,  72.64168626, 102.41924779,
         89.53387758]])

### 특정 범위 사이의 정수 (min, max, (rows, columns))

In [53]:
data = np.random.randint(0, 100, (20, 20))
data

array([[13, 82, 74, 56, 60, 89, 60, 99, 54, 20, 71,  9, 42, 39, 70, 98,
        14, 56, 85, 24],
       [92, 92, 21,  5, 16, 81, 41, 24, 43, 86, 90, 81,  2, 49, 76, 12,
         8, 62, 50, 34],
       [96, 90, 27, 84, 24,  3, 59, 66, 93, 86, 62, 73, 94, 83, 39,  1,
        21, 43, 62, 32],
       [21, 22, 63, 30, 72, 39, 33, 40, 26, 53, 37, 60,  8, 87, 73, 47,
        30, 14, 62, 98],
       [69, 55, 22, 72, 38, 18, 96, 29, 21, 15, 68, 60, 28, 10, 33, 66,
        70, 42, 31, 23],
       [28, 24, 86, 59, 57, 32, 16,  5, 43, 59, 29, 72, 72, 44,  9, 20,
         7, 89, 78, 90],
       [ 8, 21, 71, 53, 44,  1, 89, 92, 37, 65,  5, 40,  8, 12, 86, 79,
        92, 88, 10,  9],
       [92,  5, 94, 18, 15, 29, 76, 17, 99, 46, 28, 18, 11, 21, 84, 36,
        40,  4, 83, 24],
       [22,  6,  5, 59, 14, 52, 44, 84,  2, 12, 74, 22, 76, 68, 75, 89,
        72, 37,  9, 21],
       [63, 34, 75, 77, 85, 93, 24, 39, 36, 62, 62, 36, 67, 36, 88, 71,
         2,  5, 62, 39],
       [74, 17, 27,  5, 71, 21